### ISSUE TITLE
[ 코드 리뷰] Day5 미션 코드 리뷰

### ISSUE THREAD

**Issue by SungbinYang** [rimi-kim/study-all-in-one-backEnd#3]
1. 전체적으로 컨트롤러 레이어와 서비스 레이어를 나눈 레이어드 아키텍쳐 구조를 생각하시고 개발하신 점 대단하신 것 같습니다!
2. 서비스 코드
  * 기본적인 로직과 유효성 검사, 결과 집계 및 포맷팅 처리를 잘 하신 것 같습니다.
  * DTO로 응답 받는 부분도 확실히 인상 깊었습니다. 저도 이런 생각을 왜 못했는지 살짝 반성하는 계기가 되네요.
  * 성능 최적화나 예외 처리를 더 세밀하게 다룰 여지가 있을 것 같아요. 예를 들어, 매우 큰 rollCount 값에 대해 성능이 어떻게 변하는지 고려하거나, dieSide나 rollCount가 음수일 때의 처리를 추가하는 것이 좋을 수 있습니다.
3. DTO
  * 롬복을 이용해, 가독성이 좋아진 것 같네요.
  * 다만, @NoArgsConstructor와 @AllArgsConstructor 사용 시 주의할 점은, 불변 객체를 만들고자 할 때 이러한 생성자들이 그 목적에 부합하지 않을 수 있다는 것인데요. 불변성을 유지하고자 한다면, 필드에 final 키워드를 추가하고, @NoArgsConstructor 사용을 제한하거나 피해야 할 수 있습니다.
4. 컨트롤러 코드
  * 저는 Main 클래스로 Scanner를 입력받아 동작할 생각만 했는데 역으로 Restful API로 접근하는 법 정말 좋은 방식이였던 것 같습니다.
  * 컨트롤러 코드는 따로 리뷰할 사항이 없는것 같습니다.

**Comment by SungbinYang** [comment]
코드 리뷰 완료

**Comment by rimi-kim** [comment]
@SungbinYang 
감사합니다 성빈님.

항상 final 선언에 대해 이렇게 쓰는 것이 맞을까? 라는 생각 때문에 사용을 잘 못하고 있었는데
 @NoArgsConstructor와 @AllArgsConstructor 생성자와 엮어서 생각하니 이해가 빠르게 잘됐습니다.
감사합니다.

추가적으로 제어로직도 추가를 해야겠네용
